// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("AdvertCategory", Schema = "subbynetwork")]
    public partial class AdvertCategory
    {
        public AdvertCategory()
        {
            Advert = new HashSet<Advert>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Name { get; set; }
        [StringLength(255)]
        public string Slug { get; set; }
        public bool? Active { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Advert> Advert { get; set; }
    }
}