// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Advert", Schema = "subbynetwork")]
    public partial class Advert
    {
        public Advert()
        {
            ChatChannel = new HashSet<ChatChannel>();
            MediaNavigation = new HashSet<Media>();
        }

        [Key]
        public int Id { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        [StringLength(255)]
        public string ExternalLink { get; set; }
        [StringLength(255)]
        public string Postcode { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [StringLength(255)]
        public string Location { get; set; }
        [StringLength(255)]
        public string City { get; set; }
        [StringLength(255)]
        public string Price { get; set; }
        public int? Quantity { get; set; }
        [StringLength(255)]
        public string Unit { get; set; }
        [StringLength(255)]
        public string Condition { get; set; }
        public bool? IsSold { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        [Column("Category_id")]
        public int? CategoryId { get; set; }
        [Column("User_id")]
        public int? UserId { get; set; }
        [StringLength(255)]
        public string Media { get; set; }
        [StringLength(255)]
        public string Slug { get; set; }
        public bool? IsFree { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(AdvertCategory.Advert))]
        public virtual AdvertCategory Category { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Advert")]
        public virtual User User { get; set; }
        [InverseProperty("Advert")]
        public virtual ICollection<ChatChannel> ChatChannel { get; set; }
        [InverseProperty("Advert")]
        public virtual ICollection<Media> MediaNavigation { get; set; }
    }
}