// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Audit", Schema = "subbynetwork")]
    public partial class Audit
    {
        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
        [StringLength(255)]
        public string IpAddress { get; set; }
        public DateTime? RequestTime { get; set; }
        public long? ResponseMillis { get; set; }
        public int? StatusCode { get; set; }
        [StringLength(255)]
        public string Method { get; set; }
        [StringLength(255)]
        public string Path { get; set; }
        [StringLength(255)]
        public string QueryString { get; set; }
        [StringLength(255)]
        public string RequestBody { get; set; }
        [StringLength(255)]
        public string ResponseBody { get; set; }
        [StringLength(255)]
        public string UserAgent { get; set; }
        [StringLength(255)]
        public string City { get; set; }
        [Column(TypeName = "decimal(19, 5)")]
        public decimal? Latitude { get; set; }
        [Column(TypeName = "decimal(19, 5)")]
        public decimal? Longitude { get; set; }
        [StringLength(255)]
        public string Browser { get; set; }
        public int? BrowserVersion { get; set; }
        public bool? Sandbox { get; set; }
        public int? TenantId { get; set; }
        [StringLength(255)]
        public string TenantName { get; set; }
        public DateTime? CreatedAt { get; set; }
    }
}