// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("BenefitSponsor", Schema = "subbynetwork")]
    public partial class BenefitSponsor
    {
        [Key]
        public int Id { get; set; }
        [Column("Benefit_id")]
        public int? BenefitId { get; set; }
        [Column("Sponsor_id")]
        public int? SponsorId { get; set; }

        [ForeignKey(nameof(BenefitId))]
        [InverseProperty("BenefitSponsor")]
        public virtual Benefit Benefit { get; set; }
        [ForeignKey(nameof(SponsorId))]
        [InverseProperty("BenefitSponsor")]
        public virtual Sponsor Sponsor { get; set; }
    }
}