// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Benefit", Schema = "subbynetwork")]
    public partial class Benefit
    {
        public Benefit()
        {
            BenefitSponsor = new HashSet<BenefitSponsor>();
            Sponsor = new HashSet<Sponsor>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        [StringLength(255)]
        public string Slug { get; set; }
        [StringLength(255)]
        public string Image { get; set; }
        [StringLength(255)]
        public string Position { get; set; }
        public bool? Active { get; set; }

        [InverseProperty("Benefit")]
        public virtual ICollection<BenefitSponsor> BenefitSponsor { get; set; }
        [InverseProperty("Benefit")]
        public virtual ICollection<Sponsor> Sponsor { get; set; }
    }
}