// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Chat", Schema = "subbynetwork")]
    public partial class Chat
    {
        [Key]
        public int Id { get; set; }
        [Column("User_id")]
        public int? UserId { get; set; }
        [Column("Channel_id")]
        public int? ChannelId { get; set; }
        [StringLength(255)]
        public string Message { get; set; }
        public DateTime? CreatedAt { get; set; }
        [Column("isread")]
        public bool Isread { get; set; }

        [ForeignKey(nameof(ChannelId))]
        [InverseProperty(nameof(ChatChannel.Chat))]
        public virtual ChatChannel Channel { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Chat")]
        public virtual User User { get; set; }
    }
}