// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Subby.Data
{
    public partial class getAddsByPostCodeResult
    {
        public int id { get; set; }
        public string Postcode { get; set; }
        public double? Miles { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public string ExternalLink { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string Price { get; set; }
        public int? Quantity { get; set; }
        public string Unit { get; set; }
        public string Condition { get; set; }
        public bool? IsSold { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? Category_id { get; set; }
        public int? User_id { get; set; }
        public string Media { get; set; }
        public string Slug { get; set; }
        public bool? IsFree { get; set; }
    }
}
