// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Job", Schema = "subbynetwork")]
    public partial class Job
    {
        public Job()
        {
            JobActivity = new HashSet<JobActivity>();
            JobApplication = new HashSet<JobApplication>();
            JobInterest = new HashSet<JobInterest>();
            JobTrade = new HashSet<JobTrade>();
            UserReview = new HashSet<UserReview>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        [Column(TypeName = "text")]
        public string Description { get; set; }
        [StringLength(255)]
        public string Location { get; set; }
        [StringLength(255)]
        public string DeadLine { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? UserId { get; set; }
        [StringLength(255)]
        public string Latitude { get; set; }
        [StringLength(255)]
        public string Longitude { get; set; }
        [StringLength(255)]
        public string ExternalLink { get; set; }
        [StringLength(255)]
        public string Postcode { get; set; }
        [StringLength(255)]
        public string Slug { get; set; }
        [StringLength(255)]
        public string Budget { get; set; }
        public bool? IsExternal { get; set; }
        public bool? IsFeatured { get; set; }
        [StringLength(255)]
        public string ContractType { get; set; }
        [Column("User_id")]
        public int? UserId1 { get; set; }
        public int? TradeId { get; set; }
        [Column("Trade_id")]
        public int? TradeId1 { get; set; }
        public bool? IsFilled { get; set; }
        [StringLength(255)]
        public string Media { get; set; }
        [StringLength(255)]
        public string Source { get; set; }
        [StringLength(255)]
        public string Reference { get; set; }

        [ForeignKey(nameof(TradeId1))]
        [InverseProperty(nameof(Trade.Job))]
        public virtual Trade TradeId1Navigation { get; set; }
        [ForeignKey(nameof(UserId1))]
        [InverseProperty(nameof(User.Job))]
        public virtual User UserId1Navigation { get; set; }
        [InverseProperty("Job")]
        public virtual ICollection<JobActivity> JobActivity { get; set; }
        [InverseProperty("Job")]
        public virtual ICollection<JobApplication> JobApplication { get; set; }
        [InverseProperty("Job")]
        public virtual ICollection<JobInterest> JobInterest { get; set; }
        [InverseProperty("Job")]
        public virtual ICollection<JobTrade> JobTrade { get; set; }
        [InverseProperty("Job")]
        public virtual ICollection<UserReview> UserReview { get; set; }
    }
}