// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("JobActivity", Schema = "subbynetwork")]
    public partial class JobActivity
    {
        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string IpAddress { get; set; }
        public DateTime? CreatedAt { get; set; }
        [Column("Job_id")]
        public int? JobId { get; set; }
        public int? Count { get; set; }

        [ForeignKey(nameof(JobId))]
        [InverseProperty("JobActivity")]
        public virtual Job Job { get; set; }
    }
}