// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("JobInterest", Schema = "subbynetwork")]
    public partial class JobInterest
    {
        [Key]
        public int Id { get; set; }
        public bool? IsInterested { get; set; }
        public DateTime? CreatedAt { get; set; }
        [Column("Job_id")]
        public int? JobId { get; set; }
        [Column("User_id")]
        public int? UserId { get; set; }

        [ForeignKey(nameof(JobId))]
        [InverseProperty("JobInterest")]
        public virtual Job Job { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("JobInterest")]
        public virtual User User { get; set; }
    }
}