// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Media", Schema = "subbynetwork")]
    public partial class Media
    {
        public Media()
        {
            MediaMeta = new HashSet<MediaMeta>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Alt { get; set; }
        public int? Position { get; set; }
        public int? Height { get; set; }
        [StringLength(255)]
        public string MediaType { get; set; }
        [StringLength(255)]
        public string Src { get; set; }
        public int? Width { get; set; }
        [StringLength(255)]
        public string MimeType { get; set; }
        public int? Duration { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        [Column("Advert_id")]
        public int? AdvertId { get; set; }

        [ForeignKey(nameof(AdvertId))]
        [InverseProperty("MediaNavigation")]
        public virtual Advert Advert { get; set; }
        [InverseProperty("Media")]
        public virtual ICollection<MediaMeta> MediaMeta { get; set; }
    }
}