// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Sponsor", Schema = "subbynetwork")]
    public partial class Sponsor
    {
        public Sponsor()
        {
            BenefitSponsor = new HashSet<BenefitSponsor>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Name { get; set; }
        [StringLength(255)]
        public string Logo { get; set; }
        [StringLength(255)]
        public string Phone { get; set; }
        [StringLength(255)]
        public string Website { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? LiveDate { get; set; }
        [Column("Benefit_id")]
        public int? BenefitId { get; set; }

        [ForeignKey(nameof(BenefitId))]
        [InverseProperty("Sponsor")]
        public virtual Benefit Benefit { get; set; }
        [InverseProperty("Sponsor")]
        public virtual ICollection<BenefitSponsor> BenefitSponsor { get; set; }
    }
}