// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("Transaction", Schema = "subbynetwork")]
    public partial class Transaction
    {
        public Transaction()
        {
            Subscription = new HashSet<Subscription>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(19, 5)")]
        public decimal? Amount { get; set; }
        [StringLength(255)]
        public string Reference { get; set; }
        [StringLength(255)]
        public string ExternalReference { get; set; }
        [StringLength(255)]
        public string Secret { get; set; }
        [StringLength(255)]
        public string Token { get; set; }
        [StringLength(255)]
        public string Uuid { get; set; }
        [StringLength(255)]
        public string Status { get; set; }
        [Column(TypeName = "text")]
        public string Response { get; set; }
        [StringLength(255)]
        public string PaymentProvider { get; set; }
        public DateTime? CreatedAt { get; set; }
        [StringLength(255)]
        public string Currency { get; set; }
        [Column("Subscription_id")]
        public int? SubscriptionId { get; set; }

        [ForeignKey(nameof(SubscriptionId))]
        [InverseProperty("TransactionNavigation")]
        public virtual Subscription SubscriptionNavigation { get; set; }
        [InverseProperty("Transaction")]
        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}