// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Subby.Data
{
    [Table("UserTrade", Schema = "subbynetwork")]
    public partial class UserTrade
    {
        [Key]
        public int Id { get; set; }
        [Column("User_id")]
        public int? UserId { get; set; }
        [Column("Trade_id")]
        public int? TradeId { get; set; }

        [ForeignKey(nameof(TradeId))]
        [InverseProperty("UserTrade")]
        public virtual Trade Trade { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserTrade")]
        public virtual User User { get; set; }
    }
}