name: Build App
on:
  push:
    branches: [master]

jobs:
  iOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Restore packages
        run: |
          dotnet workload install maui
          dotnet workload install ios
          dotnet workload install maccatalyst
          dotnet new --install Microsoft.Maui.Templates
          nuget restore
      - name: Build iOS
        run: dotnet msbuild -t:Build -p:Configuration=Release -p:Platform=iPhone -p:BuildIpa=true ./SubbyNetwork/SubbyNetwork.csproj
